#include <iostream>
#include "Camisa.h"
#include "Pantalon.h"
#include "Maestro.h"
#include "Alumno.h"
#include "Perro.h"
#include "Gato.h"
#include <iomanip>
#include <windows.h>
using namespace std;

void establecercolorCamisa(Camisa &camisaobj, string valor){ //función que es amiga de la clase Camisa
    camisaobj.color = valor; //permite modificar el valor del atributo color por ser amiga de la clase
}
void establecermaterialPantalon(Pantalon &pantalonobj, string material){ //función que es amiga de la clase Pantalon
    pantalonobj.material = material;
}
void establecermateriaMaestro(Maestro &maestroobj, string materia){//función que es amiga de la clase Maestro
    maestroobj.materia = materia;
}
void establecercentroAlumno(Alumno &alumnoobj, string centro){ //función que es amiga de la clase Alumno
    alumnoobj.centro = centro;
}
void establecerrazaPerro(Perro &perroobj, string raza){ //función que es amiga de la clase Perro
    perroobj.raza = raza;
}
int main()
{

    HANDLE hConsole = GetStdHandle( STD_OUTPUT_HANDLE );
    cout<<"Ejercicio 1\n"<<endl;
    Camisa camisa1;
    cout<<"Se ha creado el objeto camisa1 con el constructor 1\n"<<endl;
    Camisa camisa2(937281321,1600,21, "Polo","chica", "caballero", "Azul");
    cout<<"Se ha creado el objeto camisa2 con el constructor 2 (sobrecarga de constructor)\n"<<endl;
    Camisa camisa3("Lacoste", "Dama", "grande");
    cout<<"Se ha creado el objeto camisa3 con el constructor 3 (sobrecarga de constructor)\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"-----------Metodo vender----------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    camisa1.vender();
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n----Metodo vender sobrecargado----\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    camisa1.vender(1800, 15, "Gucci");
    cout<<endl;
    system("pause");
    system("cls");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<setw(50)<<"------Metodo verificar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    camisa2.verificar();
    cout<<"\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<setw(58)<<"------Metodo verificar sobrecargado------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    camisa2.verificar(574812365, 120, "mediana", "dama");
    cout<<endl;
    system("pause");
    system("cls");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Operador binario sobrecargado-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo codigo del objeto camisa1 es: "<<camisa1.getcodigo()<<endl;
    cout<<"El atributo precio del objeto camisa2 es: "<<camisa2.getprecio()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nCon la sobrecarga del operador '/' podemos\ndividir el atributo codigo de un objeto\nentre el atributo precio de otro objeto:\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    int div;
    div = camisa1 / &camisa2;
    cout<<camisa1.getcodigo()<<" / "<<camisa2.getprecio()<<" = "<<div<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Operador unitario sobrecargado-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo descuento del objeto camisa1 es: "<<camisa1.getdescuento()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nCon la sobrecarga del operador unitario '++' podemos aumentar en 1\nel atributo descuento del objeto en cuestion"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    camisa1++;
    cout<<endl;
    cout<<"Al usar camisa1++ el atributo descuento aumenta a "<<camisa1.getdescuento()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Operadores flujo sobrecargado-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Con la sobrecarga del operador flujo '<<' podemos imprimir"<<endl;
    cout<<"los atributos marca, talla, color y tipo del objeto en cuestion"<<endl;
    cout<<"sin necesidad de escribir los gets uno por uno"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo"<<endl;
    cout<<camisa1;
    cout<<endl;
    system("pause");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Con la sobrecarga del operador flujo '>>' podemos recibir o modificar"<<endl;
    cout<<"los atributos marca, talla, color y tipo del objeto en cuestion"<<endl;
    cout<<"sin necesidad de escribir los sets uno por uno"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo"<<endl;
    cin>>camisa1;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Listo! atributos del objeto modificados"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Usando la sobrecarga del operador flujo '<<' podemos observar"<<endl;
    cout<<"que efectivamente los atributos del objeto fueron modificados"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nResultado: "<<endl;
    cout<<camisa1;
    cout<<endl;
    system("pause");
    system("cls");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Funciones amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo color del objeto camisa2 es: "<<camisa2.getcolor()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nAntes del main creamos una funcion la cual nos sirve para modificar"<<endl;
    cout<<"el atributo privado color de un objeto que sea de la clase Camisa."<<endl;
    cout<<"Esto nos es posible debido a que declaramos esa funcion como amiga"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nPor ejemplo, podemos cambiar el valor Azul por el Amarillo\n"<<endl;
    establecercolorCamisa(camisa2, "Amarillo");
    cout<<"El nuevo atributo color del objeto camisa2 es: ";
    SetConsoleTextAttribute(hConsole, 6);
    cout<<camisa2.getcolor()<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    system("cls");
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Clases amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Declaramos a la clase pantalon como amiga de la clase Camisa,"<<endl;
    cout<<"entonces ahora pantalon puede usar los atributos o metodos de camisa"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo, vamos a usar un metodo que tome el atributo codigo de camisa1 al usar un objeto de pantalon"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    Pantalon pantalon1;
    cout<<endl;
    pantalon1.metodofriend(camisa1);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Por ultimo, vamos a pasar 2 atributos de la clase pantalon a la clase camisa\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"camisa1 tiene en atributo tipo: "<<camisa1.gettipo()<<endl;
    cout<<"camisa1 tiene en atributo talla: "<<camisa1.gettalla()<<endl;
    cout<<endl;
    camisa1.settipo(pantalon1.getmaterial());
    camisa1.settalla(pantalon1.getcolor());
    cout<<"Ahora, camisa1 tiene en atributo tipo: "<<camisa1.gettipo()<<endl;
    cout<<"Ahora, camisa1 tiene en atributo talla: "<<camisa1.gettalla()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\nEjercicio 2\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El objeto pantalon1 se creo con el constructor 1\n"<<endl;
    Pantalon pantalon2(850, 4, "Algodon", "Verde", "chico");
    cout<<"El objeto pantalon2 se creo con el constructor 2 (sobrecarga de constructor)\n"<<endl;
    Pantalon pantalon3(10, "naranja", "mediano");
    cout<<"El objeto pantalon3 se creo con el constructor 3 (sobrecarga de constructor)\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Metodo bodega------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    pantalon3.bodega();
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga metodo bodega------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    pantalon3.bodega("morado");
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga de operador------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"con la sobrecarga del operador '-' podemos"<<endl;
    cout<<"restar los atributos de cantidad de los objetos\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"Ejemplo"<<endl;
    cout<<"El atributo cantidad del objeto pantalon2 es: "<<pantalon2.getcantidad()<<endl;
    cout<<"El atributo cantidad del objeto pantalon3 es: "<<pantalon3.getcantidad()<<endl;
    int resta;
    resta = pantalon3 - &pantalon2;
    cout<<pantalon3.getcantidad()<<" - "<<pantalon2.getcantidad()<<" = "<<resta<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Funciones amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo material del objeto pantalon2 es: "<<pantalon2.getmaterial()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nAntes del main creamos una funcion la cual nos sirve para modificar"<<endl;
    cout<<"el atributo privado material de un objeto que sea de la clase Pantalon."<<endl;
    cout<<"Esto nos es posible debido a que declaramos esa funcion como amiga"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nPor ejemplo, podemos cambiar Algodon por Poliester\n"<<endl;
    establecermaterialPantalon(pantalon2, "Poliester");
    cout<<"El nuevo atributo material del objeto pantalon2 es: ";
    SetConsoleTextAttribute(hConsole, 9);
    cout<<pantalon2.getmaterial()<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Clases amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Declaramos a la clase Maestro como amiga de la clase Pantalon,"<<endl;
    cout<<"entonces ahora pantalon puede usar los atributos o metodos de Pantalon"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo, vamos a usar un metodo que tome el atributo talla de pantalon2 al usar un objeto de Maestro"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    Maestro maestro1;
    cout<<endl;
    maestro1.metodofriend(pantalon2);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Por ultimo, vamos a pasar 2 atributos de la clase Maestro a la clase Pantalon\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"pantalon2 tiene en atributo material: "<<pantalon2.getmaterial()<<endl;
    cout<<"pantalon2 tiene en atributo talla: "<<pantalon2.gettalla()<<endl;
    cout<<endl;
    pantalon2.setmaterial(maestro1.getmateria());
    pantalon2.settalla(maestro1.getnombre());
    cout<<"Ahora, pantalon2 tiene en atributo material: "<<pantalon2.getmaterial()<<endl;
    cout<<"Ahora, pantalon2 tiene en atributo talla: "<<pantalon2.gettalla()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\nEjercicio 3\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El objeto maestro1 se creo con el constructor 1\n"<<endl;
    Maestro maestro2("Felipe", "Matematicas", "D88", "vespertino", 97412034);
    cout<<"El objeto maestro2 se creo con el constructor 2 (sobrecarga de constructor)\n"<<endl;
    Maestro maestro3("Quimica", "D42", 41257863);
    cout<<"El objeto maestro3 se creo con el constructor 3 (sobrecarga de constructor)\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Metodo ensenhar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    maestro2.ensenhar();
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga metodo ensenhar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    maestro2.ensenhar("Algebra");
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga de operador------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"con la sobrecarga del operador '+=' podemos"<<endl;
    cout<<"sumar enteros a los atributos codigo de los objetos\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"Ejemplo"<<endl;
    cout<<"El atributo codigo del objeto pantalon2 es: "<<maestro2.getcodigo()<<endl;
    cout<<maestro2.getcodigo()<<" + 10000000 = ";
    maestro2 += 10000000;
    cout<<maestro2.getcodigo()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Funciones amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo materia del objeto maestro3 es: "<<maestro3.getmateria()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nAntes del main creamos una funcion la cual nos sirve para modificar"<<endl;
    cout<<"el atributo privado materia de un objeto que sea de la clase Maestro."<<endl;
    cout<<"Esto nos es posible debido a que declaramos esa funcion como amiga"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nPor ejemplo, podemos cambiar Quimica por Literatura\n"<<endl;
    establecermateriaMaestro(maestro3, "Literatura");
    cout<<"El nuevo atributo material del objeto maestro3 es: ";
    SetConsoleTextAttribute(hConsole, 9);
    cout<<maestro3.getmateria()<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Clases amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Declaramos a la clase Alumno como amiga de la clase Maestro,"<<endl;
    cout<<"entonces ahora pantalon puede usar los atributos o metodos de Pantalon"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo, vamos a usar un metodo que tome el atributo nombre de maestro2 al usar un objeto de Alumno"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    Alumno alumno1;
    cout<<endl;
    alumno1.metodofriendMaestro(maestro2);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Por ultimo, vamos a pasar 2 atributos de la clase Alumno a la clase Maestro\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"maestro2 tiene en atributo seccion: "<<maestro2.getseccion()<<endl;
    cout<<"maestro2 tiene en atributo materia: "<<maestro2.getmateria()<<endl;
    cout<<endl;
    maestro2.setseccion(alumno1.getcarrera());
    maestro2.setmateria(alumno1.getcentro());
    cout<<"Ahora, maestro2 tiene en atributo seccion: "<<maestro2.getseccion()<<endl;
    cout<<"Ahora, maestro2 tiene en atributo materia: "<<maestro2.getmateria()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\nEjercicio 4\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El objeto alumno1 se creo con el constructor 1\n"<<endl;
    Alumno alumno2("Eduardo", "Arquitectura", "CUAAD", 25, 741236547);
    cout<<"El objeto alumno2 se creo con el constructor 2 (sobrecarga de constructor)\n"<<endl;
    Alumno alumno3("QFB", "CUCEI", 23);
    cout<<"El objeto alumno3 se creo con el constructor 3 (sobrecarga de constructor)\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Metodo estudiar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    alumno2.estudiar();
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga metodo estudiar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    alumno2.estudiar("CUVALLES");
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga de operador------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"con la sobrecarga del operador '>' podemos"<<endl;
    cout<<"comparar cual atributo edad de los objetos es mayor\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"Ejemplo"<<endl;
    cout<<"El atributo edad del objeto alumno2 es: "<<alumno3.getedad()<<endl;
    cout<<"El atributo edad del objeto alumno3 es: "<<alumno2.getedad()<<endl;
    if (alumno2 > &alumno3){
        cout<<"\nLa edad "<<alumno2.getedad()<<" es mayor a "<<alumno3.getedad()<<endl;
    }
    else{
        cout<<"\nLa edad "<<alumno3.getedad()<<" es mayor a "<<alumno2.getedad()<<endl;
    }
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Funciones amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo centro del objeto alumno3 es: "<<alumno3.getcentro()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nAntes del main creamos una funcion la cual nos sirve para modificar"<<endl;
    cout<<"el atributo privado centro de un objeto que sea de la clase Alumno."<<endl;
    cout<<"Esto nos es posible debido a que declaramos esa funcion como amiga"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nPor ejemplo, podemos cambiar CUCEI por CUCEA\n"<<endl;
    establecercentroAlumno(alumno3, "CUCEA");
    cout<<"El nuevo atributo centro del objeto alumno3 es: ";
    SetConsoleTextAttribute(hConsole, 9);
    cout<<alumno3.getcentro()<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Clases amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Declaramos a la clase Perro como amiga de la clase Alumno,"<<endl;
    cout<<"entonces ahora Perro puede usar los atributos o metodos de Alumno"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo, vamos a usar un metodo que tome el atributo centro de alumno2 al usar un objeto de Perro"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    Perro perro1;
    cout<<endl;
    perro1.metodofriendAlumno(alumno2);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Por ultimo, vamos a pasar 2 atributos de la clase Perro a la clase Alumno\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"alumno2 tiene en atributo nombre: "<<alumno2.getnombre()<<endl;
    cout<<"alumno2 tiene en atributo carrera: "<<alumno2.getcarrera()<<endl;
    cout<<endl;
    alumno2.setnombre(perro1.getnombre());
    alumno2.setcarrera(perro1.getraza());
    cout<<"Ahora, alumno2 tiene en atributo nombre: "<<alumno2.getnombre()<<endl;
    cout<<"Ahora, alumno2 tiene en atributo carrera: "<<alumno2.getcarrera()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\nEjercicio 5\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El objeto perro1 se creo con el constructor 1\n"<<endl;
    Perro perro2("Ruffus", "Pitbull", "Grande", "duro", 20);
    cout<<"El objeto perro2 se creo con el constructor 2 (sobrecarga de constructor)\n"<<endl;
    Perro perro3("chihuaha", "suave", 3);
    cout<<"El objeto perro3 se creo con el constructor 3 (sobrecarga de constructor)\n"<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Metodo jugar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    perro2.jugar();
    cout<<endl;
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga metodo jugar------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    perro3.jugar("pelota");
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"------Sobrecarga de operador------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"con la sobrecarga del operador '*' podemos"<<endl;
    cout<<"multiplicar los atributos de meses de 2 objetos\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"Ejemplo"<<endl;
    cout<<"El atributo meses del objeto perro3 es: "<<perro3.getmeses()<<endl;
    cout<<"El atributo meses del objeto perro2 es: "<<perro2.getmeses()<<endl;
    int mult;
    mult = perro3 * perro2;
    cout<<perro3.getmeses()<<" * "<<perro2.getmeses()<<" = "<<mult<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Funciones amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"El atributo raza del objeto perro2 es: "<<perro3.getraza()<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"\nAntes del main creamos una funcion la cual nos sirve para modificar"<<endl;
    cout<<"el atributo privado raza de un objeto que sea de la clase Alumno."<<endl;
    cout<<"Esto nos es posible debido a que declaramos esa funcion como amiga"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nPor ejemplo, podemos cambiar Pitbull por Afgano.\n"<<endl;
    establecerrazaPerro(perro2, "Afgano");
    cout<<"El nuevo atributo raza del objeto perro2 es: ";
    SetConsoleTextAttribute(hConsole, 9);
    cout<<perro2.getraza()<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"\n-------Clases amigas-------\n"<<endl;
    SetConsoleTextAttribute(hConsole, 2);
    cout<<"Declaramos a la clase Gato como amiga de la clase Perro,"<<endl;
    cout<<"entonces ahora Gato puede usar los atributos o metodos de Perro"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"\nEjemplo, vamos a usar un metodo que tome el atributo raza de perro3 al usar un objeto de Gato"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<endl;
    Gato gato1;
    gato1.metodofriendPerro(perro3);
    cout<<endl;
    system("pause");
    system("cls");
    SetConsoleTextAttribute(hConsole, 3);
    cout<<"Por ultimo, vamos a pasar 2 atributos de la clase gato a la clase Perro\n"<<endl;
    SetConsoleTextAttribute(hConsole, 7);
    cout<<"perro3 tiene en atributo raza: "<<perro3.getraza()<<endl;
    cout<<"perro3 tiene en atributo pelaje: "<<perro3.getpelaje()<<endl;
    cout<<endl;
    perro3.setraza(gato1.getnombre());
    perro3.setpelaje(gato1.getraza());
    cout<<"Ahora, perro3 tiene en atributo raza: "<<perro3.getraza()<<endl;
    cout<<"Ahora, perro3 tiene en atributo pelaje: "<<perro3.getpelaje()<<endl;
    cout<<endl;
    system("pause");
    system("cls");
    return 0;
}
